state_interfaces:
  motor_joint:
    position: float32
    velocity: float32
  pendulum_joint:
    position: float32
    velocity: float32
command_interfaces:
  motor_joint:
    acceleration: float32
