state_interfaces:
  motor_joint:
    position: float64
    velocity: float64
  pendulum_joint:
    position: float64
    velocity: float64
command_interfaces:
  motor_joint:
    acceleration: float64
