CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBC=y

CONFIG_ZENBEDDED_TIER_2=y

CONFIG_ZENBEDDED_TIER2_SCHEMA_PATH="config/interface_schema.yaml"

CONFIG_ZENBEDDED_ZENOH_IP_PORT="127.0.0.1:7447"

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_ZENBEDDED_TRANSPORT_LOG_LEVEL=3

CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000
