CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBC=y

# Enable Tier 2 (Raw Structs) instead of Tier 1 (ZCDR)
CONFIG_ZENBEDDED_TIER_1=n
CONFIG_ZENBEDDED_TIER_2=y

CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_ZENBEDDED_TRANSPORT_LOG_LEVEL=3
