# ==============================================================================
# OS Environment
# ==============================================================================
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBC=y

# ==============================================================================
# Zenbedded Integration
# (Automatically injects POSIX, Networking, Zenoh-pico, and memory buffers)
# ==============================================================================
CONFIG_ZENBEDDED_TIER_1=y

# ==============================================================================
# Simulated RCL Configuration (To be moved to RCL Kconfig later)
# ==============================================================================
CONFIG_ZENBEDDED_RCL=n
CONFIG_ZENBEDDED_RCL_DOMAIN_ID=0
CONFIG_ZENBEDDED_RCL_NODE_NAME="Zenbedded_mcu"
CONFIG_ZENBEDDED_RCL_ZENOH_MODE="client"
CONFIG_ZENBEDDED_RCL_ZENOH_LOCATOR="tcp/127.0.0.1:7447"

# ==============================================================================
# Logging Subsystem
# ==============================================================================
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
# Expose the raw Zenoh wire-traces we built in C
CONFIG_ZENBEDDED_TRANSPORT_LOG_LEVEL=2
