# ==============================================================================
# OS Environment
# ==============================================================================
CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_REQUIRES_FULL_LIBC=y

# ==============================================================================
# Zenbedded Integration
# (Automatically injects POSIX, Networking, Zenoh-pico, and memory buffers)
# ==============================================================================
CONFIG_TIER_1=y

# ==============================================================================
# Logging Subsystem
# ==============================================================================
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
# Expose the raw Zenoh wire-traces we built in C
