services:
  dev-env:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: zephyr-zenoh-dev
    volumes:
      # --- ROS 2 Workspace Volume Mounts ---
      - ../zephyr_zenoh_transport:/ros2_ws/src/zephyr_zenoh_transport
      - ../zephyr_zenoh_hardware_interface:/ros2_ws/src/zephyr_zenoh_hardware_interface

      # --- Zephyr RTOS Workspace Volume Mounts ---
      - ../zephyr_zenoh_transport:/zephyr_ws/zephyr_zenoh_transport
      - ../zephyr_firmware:/zephyr_ws/zephyr_firmware

    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
