# zephyr_firmware/prj.conf
CONFIG_TIER_1=y
CONFIG_ZENOH_PICO=y

# The exact fix from your sample_project
CONFIG_NEWLIB_LIBC=y
CONFIG_POSIX_API=y
CONFIG_POSIX_THREADS=y
CONFIG_POSIX_TIMERS=y

CONFIG_NETWORKING=y
CONFIG_NET_SOCKETS=y
CONFIG_NET_UDP=y
CONFIG_NET_IPV4=y

CONFIG_HEAP_MEM_POOL_SIZE=16384
